from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from src.core.llm_client import StructuredLLMClient
from src.rag.vector_store import VectorStore


class SubQuery(BaseModel):
    """Represents a single decomposed sub-query."""
    sub_query_id: int
    query_text: str = Field(..., description="Targeted sub-query focusing on a single specific detail.")


class QueryPlan(BaseModel):
    """Structured plan containing decomposed sub-queries."""
    original_query: str
    reasoning: str = Field(..., description="Explanation for how the query was decomposed.")
    sub_queries: List[SubQuery] = Field(..., description="List of 2-4 focused sub-queries.")


class SubQueryExecutionResult(BaseModel):
    """Result of retrieving context for an individual sub-query."""
    sub_query: SubQuery
    retrieved_contexts: List[str]
    source_ids: List[str]


class AgenticRAGResponse(BaseModel):
    """Final response generated by the Agentic RAG engine."""
    original_query: str
    query_plan: QueryPlan
    sub_query_results: List[SubQueryExecutionResult]
    final_answer: str
    aggregated_source_ids: List[str]


class AgenticRAGEngine:
    """Agentic RAG pipeline with query decomposition, parallel sub-query retrieval, and synthesis."""

    DECOMPOSITION_PROMPT = """
You are an expert search query planner. Your job is to decompose complex user queries into 2 to 4 distinct, highly focused sub-queries.
Each sub-query should isolate a specific fact, entity, or time period required to answer the overall question.
"""

    SYNTHESIS_PROMPT = """
You are an expert AI synthesis engine. Answer the user's original query using ONLY the evidence collected across multiple sub-query research steps.

Original Query: {original_query}

Collected Evidence across Sub-Queries:
{evidence_block}

Provide a complete, direct, and well-structured answer.
"""

    def __init__(self, llm_client: StructuredLLMClient, vector_store: VectorStore):
        self.llm_client = llm_client
        self.vector_store = vector_store

    def decompose_query(self, query: str) -> QueryPlan:
        """Decomposes a complex query into a structured QueryPlan."""
        user_prompt = f"Decompose this query into focused sub-queries: {query}"
        return self.llm_client.generate(
            prompt=user_prompt,
            response_schema=QueryPlan,
            system_prompt=self.DECOMPOSITION_PROMPT
        )

    def execute_plan(self, query_plan: QueryPlan, top_k: int = 2) -> List[SubQueryExecutionResult]:
        """Executes retrieval for each sub-query in the plan."""
        results = []
        for sq in query_plan.sub_queries:
            # Retrieve relevant chunks from vector store
            retrieved = self.vector_store.search(sq.query_text, top_k=top_k)
            contexts = [doc["content"] for doc in retrieved]
            sources = [doc.get("id", f"doc_{i}") for i, doc in enumerate(retrieved)]
            
            results.append(
                SubQueryExecutionResult(
                    sub_query=sq,
                    retrieved_contexts=contexts,
                    source_ids=sources
                )
            )
        return results

    def run(self, query: str, top_k_per_subquery: int = 2) -> AgenticRAGResponse:
        """Full Agentic RAG execution: Decompose -> Retrieve Sub-queries -> Synthesize."""
        # Step 1: Decompose
        plan = self.decompose_query(query)

        # Step 2: Retrieve context for each sub-query
        sub_results = self.execute_plan(plan, top_k=top_k_per_subquery)

        # Step 3: Aggregate contexts & sources
        evidence_lines = []
        aggregated_sources = set()

        for res in sub_results:
            evidence_lines.append(f"Sub-Query: '{res.sub_query.query_text}'")
            for ctx in res.retrieved_contexts:
                evidence_lines.append(f"  - Context: {ctx}")
            for src in res.source_ids:
                aggregated_sources.add(src)

        evidence_block = "\n".join(evidence_lines)

        # Step 4: Synthesize final answer using LLM Client
        synthesis_prompt = self.SYNTHESIS_PROMPT.format(
            original_query=query,
            evidence_block=evidence_block
        )

        class SynthesisOutput(BaseModel):
            answer: str

        synthesis_result = self.llm_client.generate(
            prompt=synthesis_prompt,
            response_schema=SynthesisOutput
        )

        return AgenticRAGResponse(
            original_query=query,
            query_plan=plan,
            sub_query_results=sub_results,
            final_answer=synthesis_result.answer,
            aggregated_source_ids=list(sorted(aggregated_sources))
        )
    